### ISSUE TITLE
Discuss namespacing challenges

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/Jr#2]
There are three types of namespaces involved.

1. Repository namespace (example: `JasonExtension-iOS/Websockets`) - case sensitive
2. JSON namespacing (example:  `“type”: “@websockets.connect”`) - preferably case-insensitive
3. Class name Namespacing (example: `JasonWebsocketsAction`) - case sensitive

These three are not necessarily dependent on one another and they can actually be completely different. But we don't want it to be complex. We need to figure out how to orchestrate these in the simplest way possible.

## Challenges

1. How should these three names relate to one another? - I'm thinking ideally people should only have to enter one of them and the rest can be inferred from it.
2. Can we enforce some rule so that it's the easiest for the extension users?
3. What should the UI be like for JR? And how would it operate behind the scenes?

**Comment by lukeramsden** [comment]
Labels are your friend, friend.

**Comment by lukeramsden** [comment]
I think the Class names shouldn't have any connection to the other two - only that they have to be prefixed with `Jason`, because they also might have multiple classes for one JSON type. This is good because it separates front from back. As for the other two, I think the JSON bit should be identical to the repo. `/Websockets` because `@websockets`, `/Peanut-Butter` becomes `@peanut-butter` and so on.

**Comment by gliechtenstein** [comment]
> As for the other two, I think the JSON bit should be identical to the repo. /Websockets because @websockets, /Peanut-Butter becomes @peanut-butter and so on.

=> Good idea.

> I think the Class names shouldn't have any connection to the other two - only that they have to be prefixed with Jason, because they also might have multiple classes for one JSON type.

=> The problem is if we don't enforce namespacing for the extension classes, two different extensions may end up having the same class name, and this would result in conflict. in objective-c there is no concept of folders and the class files get added in a flat structure, so having two duplicate class names will fail.

**Comment by lukeramsden** [comment]
Maybe like this - `Jason*Author**ClassName*`, like in Java where you have the packages like `com.author.package`.

**Comment by lukeramsden** [comment]
@gliechtenstein Did we figure it out?
