### ISSUE TITLE
Get form to post to jasonx

### ISSUE THREAD

**Issue by lukeramsden** [Jasonette/Jr#7]
@gliechtenstein I can't get it working, maybe you could have a go. The two files you'll probably only need are `assets/js/main.js` and `views/partials/_form.pug`

**Comment by gliechtenstein** [comment]
Ah sorry about that, the `POST` parameter is `jr[url]`, not `url`. Just remembered rails does that by default. Fixed! 

<img width="1073" alt="screen shot 2017-01-06 at 9 30 02 am" src="https://cloud.githubusercontent.com/assets/16613330/21720732/c7b13b6a-d3f2-11e6-8cbf-b4b550ad68bb.png">

**Comment by lukeramsden** [comment]
nice one @gliechtenstein 
Remember labels!
