### ISSUE TITLE
More complete error message

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/Jr#9]
When a user enters a repo url, the server checks the validity of `jr.json` and then returns an error if there's something wrong (For example the version has not been raised, etc.).

Previously we only had info on what fields are incorrect, but to actually see the value, the submitter had to go to their github page and open `jr.json` to check the values.

This is not very user friendly, so I added another field on error objects called `jr` (in addition to the error array it was returning previously)

**Let's add a simple view which displays the `jr.json` and maybe even point out the fields that need to be corrected in more contextual manner.**

**Comment by lukeramsden** [comment]
Solved by 22e74fe0c1442e77bc2aac081924cb63b261e777 and a60281ac385b12123e666063996fd7c2b25c29f5

**Comment by gliechtenstein** [comment]
> Let's add a simple view which displays the jr.json

Need to display the contents of `jr.json` along with the error messages.

**Comment by lukeramsden** [comment]
Should be doing that? It's displaying everything it gets

**Comment by lukeramsden** [comment]
@gliechtenstein It doesn't get given a `jr.json`, in object or link form

**Comment by lukeramsden** [comment]
@gliechtenstein Solved by afbd6288655999263cd7894ce5adcc55918a540f
